repos:
  - repo: local
    hooks:
      - id: check-copyright-notice
        name: check-copyright-notice
        description: Check copyright notice
        entry: python3 ../workflows-and-actions-collection/scripts/check_copyright_notice.py
        language: system
        files: \.go$
        args: []
