name: Build

on:
  workflow_call:
    inputs:
      program:
        type: string
        required: true
        description: Name of the utility to build (used for artifact name & output matching).

env:
  CALLER_DIR: 'caller-repository'
  WORKFLOW_DIR: 'workflows-and-actions-collection'

jobs:
  build:
    name: "${{ matrix.goos }} | ${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [windows, linux, darwin]
        arch: [amd64, arm64]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ github.event.repository.full_name }}
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build
        run: |
          echo "Building ${{ inputs.program }} for ${GOOS:=${{ matrix.goos }}}/${GOARCH:=${{ matrix.arch }}}"
          make OS=${{ matrix.goos }} ARCH=${{ matrix.arch }} build

      - name: Upload binary
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ inputs.program }}-${{ matrix.goos }}-${{ matrix.arch }}
          path: build/${{ inputs.program }}*
          retention-days: 7
